### ISSUE TITLE
Dependency version conflicts

### ISSUE THREAD

**Issue by xiaoshumiwm** [tencent-ailab/songgeneration#90]
# Issue: Dependency version conflicts and missing system dependencies cause runtime errors

**Description**  
After following the README instructions to set up and run the SongGeneration project, I encountered several runtime errors related to dependency versions and a missing system dependency (`ffprobe`). These issues prevented successful generation and required manual intervention to resolve.

**Environment**  
- OS: Debian 12 (bookworm)  
- Python: 3.11.2 (virtual environment)  
- CUDA: 12.4  
- GPU: NVIDIA H20  
- Project commit: latest as of 2026-03-28  

**Steps to Reproduce**  
1. Clone repository and enter directory.  
2. Create Python 3.11 virtual environment and install dependencies:  
   ```bash
   pip install -r requirements.txt
   pip install -r requirements_nodeps.txt --no-deps
   ```
3. Download runtime files and model weights as instructed.  
4. Run generation command:  
   ```bash
   sh generate.sh ./songgeneration_v2_large sample/lyrics.jsonl ./output
   ```

**Observed Errors**  

### 1. `ValueError: mutable default ...` with hydra-core  
```
ValueError: mutable default <class 'hydra.conf.JobConf.JobConfig.OverrideDirname'> for field override_dirname is not allowed: use default_factory
```
This occurred because `hydra-core==1.0.7` (as required by `requirements_nodeps.txt`) is incompatible with Python 3.11's dataclasses. Upgrading to `hydra-core==1.3.2` resolved it.

### 2. `FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe'`  
The script attempted to call `ffprobe` but it was not installed. This system dependency is not mentioned in the README. Installing `ffmpeg` (which includes `ffprobe`) fixed the issue.

### 3. `ImportError: cannot import name 'cached_download' from 'huggingface_hub'`  
After fixing the above, I encountered:
```
ImportError: cannot import name 'cached_download' from 'huggingface_hub'
```
This was due to an older `diffusers` version (0.27.2) that still uses the deprecated `cached_download` function. Upgrading `diffusers` to `0.31.0` resolved the issue.

**Temporary Workarounds Used**  
- Upgraded `hydra-core` to 1.3.2  
- Installed `ffmpeg` system-wide  
- Upgraded `diffusers` to 0.31.0  

**Suggested Fixes**  
- Update `requirements_nodeps.txt` to use compatible versions, or pin dependencies to a set known to work with Python 3.11+ and recent library updates.  
- Add `ffmpeg` as a system prerequisite in the README (or include it in the Docker image).  
- Consider adding a `requirements-latest.txt` or using `pip-tools` to manage locked versions that have been tested.  

**Additional Context**  
The project currently pins `hydra-core==1.0.7` and `diffusers==0.27.2` (implicitly via `requirements.txt` or `requirements_nodeps.txt`). However, newer versions of these libraries are required to avoid conflicts with Python 3.11 and recent `huggingface_hub`. A more flexible approach (e.g., `hydra-core>=1.3.0,<2.0`) would improve compatibility.  

Thank you for maintaining this great project! I hope this report helps improve the setup experience for others.
